### PR TITLE
Added option of hiding unavailable SL ROMS/CHDS + option of hiding ROM/CHD flags

### PR DESCRIPTION
**Pull request by Rychem28**
Added option for hiding unavailable ROM/CHDS in the SL lists

Added option to hide ROM/CHD flags (excluding clones flag) for cleaning up display of Titles

Change code for restarting Kodi audio after MAME closes. Previous code had teh built-in option of 'play' called but this does not work. Using 'resume' starts audio again after being paused and closing MAME

### CODE REVIEW

**Comment by Wintermute0110** [comment]
Thanks for your contribution. I have one request: instead of tabulators, please use spaces (4 spaces per tabulator).

**Comment by Wintermute0110** [comment]
Also, there is a lot of duplicate code. Instead of using `if condition: do rendering` it is better to use `if not condition: continue` to skip rendering. This avoids code duplication and the code is cleaner.

**Comment by Wintermute0110** [comment]
If you wish I can do the implementation myself.

**Comment by Rychem28** [comment]
If you wouldn't mind doing the above change with the if condition that would be helpful. I figured there was a better way to do the if loop without duplicating the code, I am still trying to learn all the ins and outs of python and would be interested to see how this is implemented.

**Comment by Rychem28** [comment]
Ignore the above comment, since the pull request isn't critical to the plugins operation, let me give it a whirl. I like tinkering and trying to figure things out.

One question I did have in regards to using Tab versus space, Kodi was giving me errors in regards to expected indentations not being met. I was using Notepad++ as the code editor so not sure if the issue originated there or note. Will using spaces give me the same issue? I will correct this as well.

**Comment by Rychem28** [comment]
WIntermute0110, do you mind showing me how the above it done? I have been at this few hours now and can't seem to figure it out.

Cheers

**Comment by Rychem28** [comment]
So I tired a couple more things, and I think I have come up with some more compact code. I will push this to you tomorrow for you to have a look at, cheers.

**Pull request merged**
